spring:
  datasource:
    url: jdbc:postgresql://airline-postgres/airlinedb_ticket
  security:
    oauth2:
      resourceserver:
        jwk-set-uri: http://auth-service:9000/api/auth/.well-known/jwks.json
